name = "ImmersedBodies"
uuid = "75ad5bb6-0138-40d0-96b3-a020eab9d113"
authors = ["Nick OBrien <nick4f42@proton.me>", "Arturo Burgos <burgos3@illinois.edu>", "Andres Goza <agoza@illinois.edu>", "Jared Callaham <jared.callaham@gmail.com>"]
version = "0.1.0"

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
EllipsisNotation = "1"
FFTW = "1"
FunctionWrappers = "1"
HDF5 = "0.16"
IterativeSolvers = "0.9"
LinearMaps = "3"
ProgressMeter = "1"
RecipesBase = "1"
StaticArrays = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
